### PR TITLE
CI: add flake8 to Travis

### PR DESCRIPTION
**Pull request by Kobzol**

### CODE REVIEW

**Comment by spirali** [comment]
It fails as follows: 
```
0.97s$ pip install -r requirements.txt pip install flake8

Requirement already satisfied: pip in /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages

Collecting install

  Could not find a version that satisfies the requirement install (from versions: )

No matching distribution found for install

The command "pip install -r requirements.txt pip install flake8" failed and exited with 1 during .

Your build has been stopped.
```

**Comment by Kobzol** [comment]
There was an error in my earlier commit, I rebased it and pushed it to kobzol:travis before making this PR, where do you see this error?
https://travis-ci.org/spirali/haydi/jobs/264756734 shows that the new version works.

**Comment by spirali** [comment]
I have retracted the commit, but the travis log is here: https://travis-ci.org/spirali/haydi/jobs/264757866

**Comment by Kobzol** [comment]
https://github.com/spirali/haydi/commit/c51a36f7412ecfdb653101606717451427e464d7 - this is the wrong commit
https://github.com/spirali/haydi/pull/31/commits/d15517fc0f86161fd8534ba39ec810b99a09625a - this is the correct commit, that is in this PR.

If you accept this PR, it should work, the CI checks have passed.
Sorry for the confusion, I don't know how the wrong commit got here.

**Comment by spirali** [comment]
I have repeated completely the same process (merge on master) and now it works.

So it is merged as 090e9e7f5a05a0777449d4880cd54cb08586fa5c

Thank you

**Pull request closed without merging**
